version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: audit-packages
          command: npm audit || true
      - run:
          name: test-npm
          command: npm test ||
          
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: |
            #Creating temporary certificates 
            echo "$PRIVATE_KEY" > privatekey.pem
            echo "$SERVER" > server.crt

            #Copy certificate to server
            scp -o StrictHostKeyChecking=no privatekey.pem $EC2_USERNAME@$EC2_PUBLIC_DNS:~/privatekey.pem
            scp -o StrictHostKeyChecking=no server.crt $EC2_USERNAME@$EC2_PUBLIC_DNS:~/server.crt

            rm privatekey.pem server.crt

            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS '
                    
                    if ! command -v git &> /dev/null; then
                      echo 'Git is not found.Install git'
                      sudo dnf update -y 
                      sudo dnf install -y git
                    fi

                    echo "removing old application directory"
                    rm -rf SimpleApplication_DevOps_CA/

                    echo "cloning repository"
                    git clone https://github.com/SanRob1325/SimpleApplication_DevOps_CA.git

                    echo "Setting up execution by granting permissions"
                    chmod +x SimpleApplication_DevOps_CA/deploy.sh
                    
                    echo 'Preparing HTTPS certificates for security'
                    mv ~/privatekey.pem ~/server.crt SimpleApplication_DevOps_CA/
                    chmod 600 SimpleApplication_DevOps_CA/privatekey.pem SimpleApplication_DevOps_CA/server.crt

                    echo "Adding deployment sh script"
                    cd SimpleApplication_DevOps_CA && bash deploy.sh
                  '
