version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
          
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
                    
                    which git || sudo yum update -y && sudo yum install -y git
                    rm -rf SimpleApplication_DevOps_CA/
                    git clone https://github.com/SanRob1325/SimpleApplication_DevOps_CA.git

                    chmod +x SimpleApplication_DevOps_CA/deploy.sh

                    bash SimpleApplication_DevOps_CA/deploy.sh
                  "